### ISSUE TITLE
Open same Tab

### ISSUE THREAD

**Issue by mr8tom** [thevahidal/github-actions-python#2]
Hello, where can I change in the Sourcecode, that the Link will be opened in the same Tab? I don't want it to be opened in a new tab.
Thank you! :)
<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💸Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount)<br/>💪 If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #2</code> either in the PR description or in a PR's comment<br/><br/>👀 Also, everyone can tip any user commenting <code>/tip 20 @mr8tom</code> (replace <code>20</code> with the amount, and <code>@mr8tom</code> with the user to tip)<br/><br/>If you want to learn more, go to our <a href="https://docs.opire.dev">documentation</a></details>

**Comment by thevahidal** [comment]
Hey @mr8tom 
Here (https://github.com/thevahidal/jake/blob/main/script.py#L29) you can change this behavior, just remove target="_blank".

**Comment by thevahidal** [comment]
Also it would nice if you add a feature to Jake to allow users do this via data.toml config file.
